name: Test

on: [push]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: execute tests
        run: curl "https://raw.githubusercontent.com/schul-cloud/integration-tests/develop/scripts/ci/fetch.github.sh" | bash
      - uses: actions/upload-artifact@v1
        name: upload results
        if: always()
        with:
          name: report
          path: integration-tests/reports
