name: Test

on: [push]

jobs:
  integration:
    container: arjun27/playwright-bionic:0.2.0
    steps:
      - name: execute tests
        run: curl "https://raw.githubusercontent.com/schul-cloud/integration-tests/develop/scripts/ci/fetch.github.sh" | bash
      - uses: actions/upload-artifact@v1
        name: upload results
        if: always()
        with:
          name: report
          path: integration-tests/reports
